name = "trwa/smtt"
version = "0.0.0"
compiler = "v1.1.3"
plutus = "v3"
license = "AGPL-3.0"
description = "Aiken tag minting for the paper 'Secure Distributed State Management in eUTxO Blockchains'"

[repository]
user = "trwa"
project = "smtt"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
